### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Nowaker** [Shingyx/restart-karabiner-on-wake#2]
```
nowaker@nwkr-newmbp ~ % /Users/nowaker/projects/nowaker/restart-karabiner-on-wake/main.swift
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2/libxml/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2/libxml/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
... (hundreds of lines)
```

Some most relevant (in my opinion) lines:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/xpc/xpc.h:6:10: error: could not build module 'os_object'
#include <os/object.h>

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:10: error: could not build module 'CoreServices'
#include <CoreServices/CoreServices.h>

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ImageIO.h"
```

Any ideas?

**Comment by Shingyx** [comment]
Hi there. Two things come to mind:

* Do you have the latest version of XCode installed? I believe this is required to compile it.
* Have you tried using the pre-compiled version instead? You can find the binary in the latest GitHub release here https://github.com/Shingyx/restart-karabiner-on-wake/releases/latest. There is a setup guide in the README.

Thanks.

**Comment by Nowaker** [comment]
> Do you have the latest version of XCode installed? I believe this is required to compile it.

Gotcha. That must be it. I don't have XCode. I only have the minimum required to run `brew` & stuff. I'll install it and try again. Thanks.

> Have you tried using the pre-compiled version instead?

No, as I wanted to customize the script a bit to run different commands.

**Comment by Nowaker** [comment]
I had to install Xcode.app, and then execute `sudo xcode-select --reset` to make it work. Thanks!
